#%RAML 1.0
title: Industry Codes
version: v1
baseUri: /

types:
  GeneralCode:
    properties:
      ISO_Description: string
      ISO_CGL: string
      bottomLine_y: number
      page: number
  SpecificCode:
    properties:
      SIC: string
      NAICS: string
      generalDescription: string
      NCCI: string
      CA_WC: string
      DE_WC: string
      MI_WC: string
      NJ_WC: string
      NY_WC: string
      PA_WC: string
      TX_WC: string
      row_y: number
      page: number

resourceTypes:


/:
  get:
    queryParameters: