#%RAML 1.0
title: Industry Codes
version: v1
baseUri: /

types:
  IndustryCode:
    properties:
      ISO_Description: string
      ISO_CGL: string
      SIC: string
      NAICS: string
      generalDescription: string
      NCCI: string
      CA_WC: string
      DE_WC: string
      MI_WC: string
      NJ_WC: string
      NY_WC: string
      PA_WC: string
      TX_WC: string
    example:

resourceTypes:


/:
  get:
    queryParameters: